export const data = [
    {
        brand: "Backpacker's Pantry",
        name: 'Blueberry Walnut Oats',
        type: ['breakfast'],
        calories: 420,
        waterML: 240,
        waterTemp: 'boiling',
        minutes: 5,
        allergens: ['tree nuts'],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Cinnamon Apple Oats',
        type: ['breakfast'],
        calories: 440,
        waterML: 300,
        waterTemp: 'boiling',
        minutes: 5,
        allergens: ['milk'],
        special: ['glutenFree', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Granola with Bananas & Milk',
        type: ['breakfast'],
        calories: 620,
        waterML: 240,
        waterTemp: 'cold or hot',
        minutes: 0,
        allergens: ['milk', 'coconut', 'almonds'],
        special: ['glutenFree', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Granola with Blueberries, Almonds & Milk',
        type: ['breakfast'],
        calories: 620,
        waterML: 240,
        waterTemp: 'cold or hot',
        minutes: 0,
        allergens: ['milk', 'coconut', 'almonds'],
        special: ['glutenFree', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Mango Sticky Rice',
        type: ['breakfast', 'dessert'],
        calories: 620,
        waterML: 360,
        waterTemp: 'boiling',
        minutes: 8,
        allergens: ['coconut'],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Peanut Butter Banana Oatmeal',
        type: ['breakfast'],
        calories: 520,
        waterML: 240,
        waterTemp: 'boiling',
        minutes: 5,
        allergens: ['peanut'],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Rocky Mountain Scramble',
        type: ['breakfast'],
        calories: 280,
        waterML: 300,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['egg', 'milk'],
        special: ['glutenFree']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Summit Breakfast Scramble',
        type: ['breakfast'],
        calories: 260,
        waterML: 300,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['egg', 'milk'],
        special: ['glutenFree']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Astro Neopolitan Ice Cream Sandwich',
        type: ['dessert'],
        calories: 130,
        waterML: 0,
        waterTemp: 'no rehydration necessary',
        minutes: 0,
        allergens: ['milk', 'soy', 'wheat', 'gluten'],
        special: ['vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Astro Vanilla Ice Cream Sandwich',
        type: ['dessert'],
        calories: 130,
        waterML: 0,
        waterTemp: 'no rehydration necessary',
        minutes: 0,
        allergens: ['milk', 'soy', 'wheat', 'gluten'],
        special: ['vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Creme Brulee',
        type: ['dessert'],
        calories: 610,
        waterML: 180,
        waterTemp: 'cold',
        minutes: 12,
        allergens: ['milk', 'soy'],
        special: ['glutenFree', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Dark Chocolate Cheesecake Mix',
        type: ['dessert'],
        calories: 600,
        waterML: 160,
        waterTemp: 'cold',
        minutes: 12,
        allergens: ['milk', 'soy', 'wheat', 'gluten'],
        special: ['vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Chana Masala',
        type: ['entree'],
        calories: 860,
        waterML: 540,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['coconut'],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Chicken Lasagna',
        type: ['entree'],
        calories: 370,
        waterML: 300,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['wheat', 'egg', 'milk'],
        special: []
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Cuban Coconut Rice & Black Beans',
        type: ['entree'],
        calories: 750,
        waterML: 540,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['coconut'],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Fetuccini Alfredo with Chicken',
        type: ['entree'],
        calories: 720,
        waterML: 480,
        waterTemp: 'boiling',
        minutes: 20,
        allergens: ['milk', 'wheat', 'gluten'],
        special: []
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Hatch Green Chili Mac & Cheese',
        type: ['entree'],
        calories: 300,
        waterML: 180,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['wheat', 'egg', 'milk'],
        special: []
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Kathmandu Curry',
        type: ['entree'],
        calories: 670,
        waterML: 650,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: [],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Lasagna',
        type: ['entree'],
        calories: 680,
        waterML: 480,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['wheat', 'egg', 'milk', 'soy'],
        special: ['vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Louisiana Red Beans & Rice',
        type: ['entree'],
        calories: 330,
        waterML: 300,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: [],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Mashed Potatoes with Gravy & Beef',
        type: ['entree'],
        calories: 360,
        waterML: 480,
        waterTemp: 'boiling',
        minutes: 20,
        allergens: ['milk'],
        special: ['glutenFree']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Mushroom Stroganoff',
        type: ['entree'],
        calories: 590,
        waterML: 480,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['wheat', 'egg', 'milk'],
        special: []
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Pad Thai',
        type: ['entree'],
        calories: 930,
        waterML: 540,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['peanuts', 'soy'],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Pad Thai with Chicken',
        type: ['entree'],
        calories: 840,
        waterML: 480,
        waterTemp: 'boiling',
        minutes: 20,
        allergens: ['peanuts'],
        special: ['glutenFree']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Pasta Primavera',
        type: ['entree'],
        calories: 330,
        waterML: 300,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['wheat', 'eggs', 'milk'],
        special: ['vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Rice & Chicken',
        type: ['entree'],
        calories: 310,
        waterML: 180,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['milk'],
        special: []
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Risotto with Chicken',
        type: ['entree'],
        calories: 600,
        waterML: 470,
        waterTemp: 'boiling',
        minutes: 20,
        allergens: ['milk', 'soy'],
        special: ['glutenFree']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Santa Fe Style Rice & Beans with Chicken',
        type: ['entree'],
        calories: 680,
        waterML: 480,
        waterTemp: 'boiling',
        minutes: 20,
        allergens: ['milk', 'soy'],
        special: ['glutenFree']
    },
    {
        brand: "Backpacker's Pantry",
        name: "Shepherd's Potato Stew with Beef",
        type: ['entree'],
        calories: 460,
        waterML: 530,
        waterTemp: 'boiling',
        minutes: 20,
        allergens: ['milk'],
        special: ['glutenFree']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Stroganoff Sauce, Egg Noodles, Beef & Mushrooms',
        type: ['entree'],
        calories: 600,
        waterML: 600,
        waterTemp: 'boiling',
        minutes: 20,
        allergens: ['milk', 'wheat', 'gluten'],
        special: []
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Three Amigos Veggie Stew',
        type: ['entree'],
        calories: 560,
        waterML: 420,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: [],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
    {
        brand: "Backpacker's Pantry",
        name: 'Three Cheese Mac & Cheese',
        type: ['entree'],
        calories: 860,
        waterML: 480,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: ['eggs', 'milk', 'wheat', 'gluten'],
        special: ['vegetarian']
    },{
        brand: "Backpacker's Pantry",
        name: 'Three Sisters Stew',
        type: ['entree'],
        calories: 720,
        waterML: 540,
        waterTemp: 'boiling',
        minutes: 15,
        allergens: [],
        special: ['glutenFree', 'vegan', 'vegetarian']
    },
]
